name: action-config-create-minimal-example
note: |-
  ```yaml
  configVersion: "1"
  action: create
  discovery:
    root: .
    noGitignore: false
  filter:
    inline: return true
  map:
    inline: return { meta = { created = true } }
  output:
    lines: false
    pretty: true
    out: "-"
  save:
    enabled: false
    onExists: ignore
    hashLen: 15
  ```
labels:
  - design
